apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init-job
  namespace: quiz-app
spec:
  template:
    spec:
      containers:
        - name: mongo-init
          image: ogochukwuozotta/database:addb3e7245b170423d2ef8cd0b093cda8596318a
          env:
            - name: MONGO_HOST
              value: "mongodb-svc"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DB
              value: "quiz_database"
      restartPolicy: Never
  backoffLimit: 4