apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init-job
  namespace: quiz-app
spec:
  template:
    spec:
      containers:
        - name: mongo-init
          image: ogochukwuozotta/database:70a67e3a86e4e50f003513db652c7c90ddcb79e7
          env:
            - name: MONGO_HOST
              value: "mongodb-svc"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DB
              value: "quiz_database"
      restartPolicy: Never
  backoffLimit: 4